### ISSUE TITLE
Pufferpanel - Config.json Permission Denied

### ISSUE THREAD

**Issue by Kelambrad** [YunoHost-Apps/pufferpanel_ynh#11]
### Describe the bug

Pufferpanel failed to start, log states;
[ERROR] 2023/01/24 11:40:17 error saving session key: open /etc/pufferpanel/config.json: permission denied

### Context

- Hardware: Dedicated machine, i5 6500, 16gb, 256gb SSD.
- YunoHost version: 11.0.11
- I have access to my server: Admin Panel, Keyboard&Mouse and SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: 
pufferpanel 2.4.0~ynh1
- If upgrading, current package version: N/A

### Steps to reproduce
Install Pufferpanel via webadmin page,
assign to specific domain,
installation completes successfully,
application refuses to start.

### Expected behavior
Install Pufferpanel via webadmin page,
assign to specific domain,
installation completes successfully,
Application starts succesfully.

### Logs
https://paste.yunohost.org/raw/nufixevawe

**Comment by ericgaspar** [comment]
fixed with #10
